export enum AttachmentModule {
  PROCESS = 'PROCESS',
  ITEM = 'ITEM',
  WORK_CENTRE = 'WORK_CENTRE',
  USER = 'USER',
  COMPANY = 'COMPANY',
  BOM = 'BOM',
  PRODUCTION_ORDER = 'PRODUCTION_ORDER',
  MATERIAL_REQUEST = 'MATERIAL_REQUEST',
}

